import { ROUTES } from "./routes";

export const resourceAndOperation = {
  operationList: {
    CREATE: "create",
    UPDATE: "update",
    GETALL: "getAll",
    GETONE: "getOne",
    DELETE: "delete",
    SOFTDELETE: "softDelete",
    RESTORE: "restore",
    GETDELETED: "getDeleted",
    SEARCH: "search",
    BATCHDELETE: "batchDelete",
    BATCHRESTORE: "batchRestore",
  },
  resourceList: {
    YEGAN: "yegans",
    AMELE_KHARID: "amel_kharids",
    EMZA_TANKHAH: "emza_conts",
    EMZA_SANAD_BARGASHTI: "emza_sanad_barghashtis",
    EMZA_TAKHSIS: "emza_yegans",
    YEGAN_VAGOZAR: "yegan_vagozars",
    FAALIAT: "faaliats",
    BARNAME: "barnames",
    CREDITBUDGET: "credit_origin_budgets",
    CREDITNONBUDGET: "credit_origin_non_budgets",
    JABEJAEETEBARS: "jabejae_etebars",
    GHERMEZETEBAR: "ghermez_etebars",
    // TAKHSISETEBAR: "takhsis_eteabars",
    TAKHSISETEBAR: "takhsis_etebars",
    ACTION: "actions",
    TANKHAH: "tankhahs",
    PREPAYMENTS: "pre_payments",
    PARDAKHTTAJMIEE: "pardakht_tajmiees",
    NAGDPARDAKHT: "naghd_pardakhts",
    ELEMEBARGASHTI: "elam_barghashtis",
    PERSONALINFOS: "personal_infos",
    YEGANVAGOZAR: "yegan_vagozars",
    PERSONS: "persons",
    PERMISSIONS: "permissions",
    USERS: "users",
    ROLES: "roles",
    ADDCREDITS: "add_credits",
    PEYMANKAR: "peymankars",
  },
};

export const listItems = [
  {
    id: 1,
    parentId: null,
    nameKey: "yegans",
    title: "ثبت یگان",
    path: ROUTES.SETTINGS.YEGAN,
    icon: "mdi-light:settings",
    caption: "",
    sectionId: 1,
    sectionKey: "yegan",
  },
  {
    id: 2,
    parentId: null,
    nameKey: "amel_kharids",
    title: "عامل خرید ",
    path: ROUTES.SETTINGS.AMELE_KHARID,
    icon: "mdi-light:clipboard-plus",
    caption: "",
    sectionId: 1,
    sectionKey: "amele_kharid",
  },

  {
    id: 6,
    parentId: null,
    nameKey: "yegan_vagozars",
    title: " ثبت اطلاعات یگان واگذار ",
    path: ROUTES.SETTINGS.YEGAN_VAGOZAR,
    icon: "mdi-light:face-mask",
    caption: "",
    sectionId: 1,
    sectionKey: "yegan_vagozar",
  },
  {
    id: 35,
    parentId: null,
    nameKey: "peyman_kars",
    title: " پیمانکار ",
    path: ROUTES.SETTINGS.PEYMANKAR,
    icon: "mdi-light:ungroup",
    caption: "",
    sectionId: 1,
    sectionKey: "peymankar",
  },

  {
    id: 7,
    parentId: null,
    nameKey: "faaliats",
    title: " فعالیت ",
    path: ROUTES.SETTINGS.FAALIAT,
    icon: "mdi-light:ungroup",
    caption: "",
    sectionId: 1,
    sectionKey: "faliat",
  },
  {
    id: 8,
    parentId: null,
    nameKey: "barnames",
    title: " برنامه",
    path: ROUTES.SETTINGS.BARNAME,
    icon: "mdi-light:tab-plus",
    caption: "",
    sectionId: 1,
    sectionKey: "barname",
  },
  {
    id: 3,
    parentId: null,
    nameKey: "emza_yegans",
    title: " ثبت امضاکنندگان تنخواه ",
    path: ROUTES.SETTINGS.EMZA_TANKHAH,
    icon: "mdi-light:baseball-diamond",
    caption: "",
    sectionId: 1,
    sectionKey: "emza_tankha",
  },
  {
    id: 4,
    parentId: null,
    nameKey: "emza_yegans",
    title: "ثبت امضاکنندگان سند برگشتی",
    path: ROUTES.SETTINGS.EMZA_SANAD_BARGASHTI,
    icon: "mdi-light:baseball-diamond",
    caption: "",
    sectionId: 1,
    sectionKey: "emza_sanad_bargashti",
  },
  {
    id: 5,
    parentId: null,
    nameKey: "emza_yegans",
    title: " ثبت امضاء کنندگان تخصیص ",
    path: ROUTES.SETTINGS.EMZA_TAKHSIS,
    icon: "mdi-light:baseball-diamond",
    caption: "",
    sectionId: 1,
    sectionKey: "emza_takhsis",
  },
  {
    id: 9,
    parentId: null,
    nameKey: "credit_origin_budgets",
    title: "اعتبارات بودجه ای ",
    icon: "mdi-light:credit-card-scan",
    caption: "",
    sectionId: 2,
    sectionKey: "credit_origin_budget",
  },
  {
    id: 10,
    parentId: 9,
    nameKey: "credit_origin_budgets",
    title: "  ثبت اعتبار / برگ اعتبار  ",
    path: ROUTES.BUDGET.CREDIT,
    icon: "mdi-light:note-text",
    caption: "",
    sectionId: 2,
    sectionKey: "sabt_brg_bodjee",
  },
  {
    id: 11,
    parentId: 9,
    nameKey: "credit_origin_budgets",
    title: "ثبت تخصیص اعتبار",
    path: ROUTES.BUDGET.TAKHSIS,
    icon: "mdi-light:note-text",
    caption: "",
    sectionId: 2,
    sectionKey: "sabt_takhsis_etebar",
  },
  {
    id: 12,
    parentId: 9,
    nameKey: "credit_origin_budgets",
    title: "ثبت تنخواه / نقدپرداخت ",
    path: ROUTES.BUDGET.TANKHAH,
    icon: "mdi-light:format-float-none",
    caption: "",
    sectionId: 2,
    sectionKey: "sabt_tankhah_etebar",
  },
  {
    id: 13,
    parentId: 9,
    nameKey: "credit_origin_budgets",
    title: " ثبت سند برگشتی / اعلامیه برگشتی ",
    path: ROUTES.BUDGET.ELAMIE,
    icon: "mdi-light:format-float-none",
    caption: "",
    sectionId: 2,
    sectionKey: "sabt_sanad_bargashti",
  },
  {
    id: 14,
    parentId: null,
    nameKey: "credit_origin_non_budgets",
    title: "اعتبارات غیر بودجه ای ",
    icon: "mdi-light:briefcase",
    caption: "",
    sectionId: 2,
    sectionKey: "credit_origin_non_budget",
  },
  {
    id: 15,
    parentId: 14,
    sectionId: 2,
    nameKey: "credit_origin_non_budgets",
    title: "  ثبت اعتبار / برگ اعتبار  ",
    path: ROUTES.BUDGET.NON_CREDIT,
    icon: "mdi-light:note-text",
    caption: "",
    sectionKey: "sabt_barg_gheyr_bodjee",
  },
  {
    id: 16,
    parentId: 14,
    sectionId: 2,
    nameKey: "credit_origin_non_budgets",
    title: "ثبت تخصیص اعتبار",
    path: ROUTES.BUDGET.NON_TAKHSIS,
    icon: "mdi-light:note-text",
    caption: "",
    sectionKey: "sabt_takhssis_gheyr_bodjee",
  },
  {
    id: 17,
    parentId: 14,
    nameKey: "credit_origin_non_budgets",
    title: "ثبت تنخواه / نقدپرداخت ",
    path: ROUTES.BUDGET.NON_TANKHAH,
    icon: "mdi-light:format-float-none",
    caption: "",
    sectionId: 2,
    sectionKey: "sabt_tankhsh_gheyr_bodjee",
  },
  {
    id: 18,
    parentId: 14,
    nameKey: "credit_origin_non_budgets",
    title: " ثبت سند برگشتی / اعلامیه برگشتی ",
    path: ROUTES.BUDGET.NON_ELAMIE,
    icon: "mdi-light:format-float-none",
    caption: "",
    sectionId: 2,
    sectionKey: "sabt_sanad_bargashti",
  },
  {
    id: 19,
    parentId: null,
    nameKey: "pre_payments",
    title: "ثبت  اضافه کار",
    path: ROUTES.EZAFEKAR.FORM,
    icon: "mdi-light:chart-pie",
    caption: "",
    sectionId: 3,
    sectionKey: "sabt_ezafekar",
  },
  {
    id: 20,
    parentId: null,
    nameKey: "pre_payments",
    title: "   گزارشات",
    path: ROUTES.EZAFEKAR.REPORT,
    icon: "mdi-light:chart-bar",
    caption: "",
    sectionId: 3,
    sectionKey: "gozaresh_ezafekar",
  },
  {
    id: 21,
    parentId: null,
    nameKey: "padashes",
    title: "ثبت پاداش",
    path: ROUTES.PADASH.FORM,
    icon: "",
    caption: "",
    sectionId: 4,
    sectionKey: "sabt_padash",
  },
  {
    id: 22,
    parentId: null,
    nameKey: "padashes",
    title: "گزارشات",
    path: ROUTES.PADASH.REPORT,
    icon: "",
    caption: "",
    sectionId: 4,
    sectionKey: "gozaresh_padash",
  },
  {
    id: 23,
    parentId: null,
    nameKey: "padashes",
    title: "ثبت اطلاعات پایه",
    path: ROUTES.PADASH.SETTINGS,
    icon: "",
    caption: "",
    sectionId: 4,
    sectionKey: "sabt_etelat_paye",
  },
  {
    id: 24,
    parentId: null,
    nameKey: "ghermez_etebars",
    title: "ثبت قرمز کردن اعتبار ",
    path: ROUTES.TRANSFERS.GHERMEZ,
    icon: "",
    caption: "",
    sectionId: 5,
    sectionKey: "sabt_ghermez_etebar",
  },
  {
    id: 26,
    parentId: null,
    nameKey: "ghermez_etebars",
    title: "گزارشات قرمز کردن ",
    path: ROUTES.TRANSFERS.GHERMEZ_REPORT,
    icon: "",
    caption: "",
    sectionId: 5,
    sectionKey: "gozaresh_ghermez_etebar",
  },
  {
    id: 25,
    parentId: null,
    nameKey: "jabejae_etebars",
    title: "ثبت جابجایی",
    path: ROUTES.TRANSFERS.JABEJAE,
    icon: "",
    caption: "",
    sectionId: 5,
    sectionKey: "sabt_jabejae_etebar",
  },
  {
    id: 27,
    parentId: null,
    nameKey: "jabejae_etebars",
    title: "گزارشات جابجایی",
    path: ROUTES.TRANSFERS.JABEJAE_REPORT,
    icon: "",
    caption: "",
    sectionId: 5,
    sectionKey: "gozaresh_jabejae_etebar",
  },
  {
    id: 28,
    parentId: null,
    nameKey: "persons",
    title: " مدیریت پرسنل",
    path: ROUTES.USERS.PERSONS,
    icon: "",
    caption: "",
    sectionId: 6,
    sectionKey: "managment_person",
  },
  {
    id: 29,
    parentId: null,
    nameKey: "users",
    title: "مدیریت ادمین ها",
    path: ROUTES.USERS.ADMINS,
    icon: "",
    caption: "",
    sectionId: 6,
    sectionKey: "managment_user",
  },
  {
    id: 30,
    parentId: null,
    nameKey: "roles",
    title: " مدیریت نقش ها",
    path: ROUTES.USERS.ROLES,
    icon: "",
    caption: "",
    sectionId: 6,
    sectionKey: "managment_role",
  },
  {
    id: 33,
    parentId: null,
    nameKey: "roles",
    title: " مدیریت دسترسی  ها",
    path: ROUTES.USERS.PERMISSION,
    icon: "",
    caption: "",
    sectionId: 6,
    sectionKey: "managment_role",
  },
  {
    id: 31,
    parentId: null,
    nameKey: "users",
    title: "   گزارش ورود و خروج ",
    path: ROUTES.USERS.AUTH_REPORT,
    icon: "",
    caption: "",
    sectionId: 7,
    sectionKey: "sign_in_sign_up",
  },
  {
    id: 32,
    parentId: null,
    nameKey: "my_profile",
    title: "  پروفایل ",
    path: ROUTES.PROFILE,
    icon: "",
    caption: "",
    sectionId: 8,
  },
  {
    id: 10,
    parentId: null,
    nameKey: "",
    title: "ثبت یگان",
    path: "/",
    icon: "",
    caption: "",
    sectionId: 1,
  },
];
